# Generated by Django 5.2.5 on 2025-08-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0002_tarea_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
